openapi: 3.0.0
info:
  title: Information générales sur l'application
  version: 1.0.0
tags:
  - name: infos
    description: Information générales sur l'application
paths:
  /:
    summary: Information générales sur l'application
    description: récupération d'informations générales sur l'application
    get:
      tags: [ infos ]
      summary: informations sur l'application
      description: récupération d'informations générales sur l'application
      responses:
        200:
          $ref: "responses.yml#/infos"
